title: Config
description: Config defines the a resource configuration.
type: object

properties:
  version:
    description: Version defines the schema version.
    type:
      - string
      - number
  type:
    type: string
    description: Type defines the schema type.
    enum:
      - environment
      - pipeline
      - template
      - service

required:
- type

oneOf:
- allOf:
  - properties:
      type:
        const: pipeline
  - properties:
      spec:
        $ref: ./pipeline.yaml
