type: object
title: Default

properties:
  clone:
    $ref: ./clone.yaml
    description: Configures the default clone behavior.
  repository:
    $ref: ./repository.yaml
    description: Configures the default repository.
  registry:
    $ref: ./registry.yaml
    description: Provides the default registry credentials.
  resources:
    $ref: ./resources.yaml
    description: Configures the default stage and step resources.
  delegate:
    description: Configures the default delegate matching logic.
    anyOf:
    - items:
        type: string
      type: array
    - type: string
  barriers:
    items:
      $ref: ./barrier.yaml
    type: array
  status:
    $ref: ./status.yaml
    description: Configures the scm status checks.
  timeout:
    type: string
    description: Configures the pipeline timeout.
  envs:
    type: object
    additionalProperties:
      type: string
    description: Provides the default environment variables.

x-docs-skip: false
x-docs-title: pipeline.options